[libraries]
classgraph = "io.github.classgraph:classgraph:4.8.151"
interop-common = "com.projectronin.interop:interop-common:3.1.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.1.0"
jackson-core = "com.fasterxml.jackson.core:jackson-core:2.14.1"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.14.1"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.14.1"
mockk = "io.mockk:mockk:1.13.3"
