[libraries]
classgraph = "io.github.classgraph:classgraph:4.8.146"
fhir-validation = "ca.uhn.hapi.fhir:org.hl7.fhir.validation:5.6.45"
interop-common = "com.projectronin.interop:interop-common:1.0.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:1.0.0"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.2"
mockk = "io.mockk:mockk:1.12.4"
