[libraries]
classgraph = "io.github.classgraph:classgraph:4.8.149"
interop-common = "com.projectronin.interop:interop-common:2.1.1"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:2.1.1"
jackson-core = "com.fasterxml.jackson.core:jackson-core:2.13.3"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.13.3"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3"
mockk = "io.mockk:mockk:1.12.4"
