[libraries]
classgraph = "io.github.classgraph:classgraph:4.8.160"
interop-common = "com.projectronin.interop:interop-common:3.7.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.7.0"

jackson-core = "com.fasterxml.jackson.core:jackson-core:2.15.1"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.15.1"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.15.1"
datafaker = "net.datafaker:datafaker:1.9.0"
mockk = "io.mockk:mockk:1.13.5"
ronin-test-data-generator = "com.projectronin.test:ronin-test-data-generator:0.0.2"
