name: Lint
on:
  push:
    branches: [ main, refactor ]
  pull_request:

jobs:
  build:
    runs-on: oci-shared
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradlew Ktlint
        run: ./gradlew ktlintCheck
