package com.projectronin.interop.fhir.r4.valueset

import com.fasterxml.jackson.annotation.JsonValue
import com.projectronin.interop.common.enums.CodedEnum

/**
 * See [FHIR Spec](https://hl7.org/fhir/r4/valueset-document-relationship-type.html)
 */
enum class DocumentRelationshipType(@JsonValue override val code: String) : CodedEnum<DocumentRelationshipType> {
    /**
     * This document logically replaces or supersedes the target document.
     */
    REPLACES("replaces"),

    /**
     * This document was generated by transforming the target document (e.g. format or language conversion).
     */
    TRANSFORMS("transforms"),

    /**
     * This document is a signature of the target document.
     */
    SIGNS("signs"),

    /**
     * This document adds additional information to the target document.
     */
    APPENDS("appends")
}
